version = 0.1

[default.deploy.parameters]
stack_name = "slack-gpt-bot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vh5n06om7r82"
s3_prefix = "slack-gpt-bot"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
